// TODO Rename keys to match actual icon? These are based on a mix of KeepassXC
//      and Keepass names but they don't match some of the icons.
const DefaultIconNumber = Object.freeze({
  Password: 0,
  PackageNetwork: 1,
  MessageBoxWarning: 2,
  Server: 3,
  Klipper: 4,
  EduLanguages: 5,
  KCMDF: 6,
  Kate: 7,
  Socket: 8,
  Identity: 9,
  Kontact: 10,
  Camera: 11,
  IrKickFlash: 12,
  KGPGKey3: 13,
  LaptopPower: 14,
  Scanner: 15,
  MozillaFirebird: 16,
  CdromUnmount: 17,
  Display: 18,
  MailGeneric: 19,
  Misc: 20,
  KOrganizer: 21,
  ASCII: 22,
  Icons: 23,
  ConnectEstablished: 24,
  FolderMail: 25,
  FileSave: 26,
  NfsUnmount: 27,
  QuickTime: 28,
  KGPGTerm: 29,
  Konsole: 30,
  FilePrint: 31,
  FSView: 32,
  Run: 33,
  Configure: 34,
  KRFB: 35,
  Ark: 36,
  KPercentage: 37,
  SambaUnmount: 38,
  History: 39,
  MailFind: 40,
  VectorGfx: 41,
  KCMMemory: 42,
  EditTrash: 43,
  KNotes: 44,
  Cancel: 45,
  Help: 46,
  KPackage: 47,
  Folder: 48,
  FolderBlueOpen: 49,
  FolderTar: 50,
  Decrypted: 51,
  Encrypted: 52,
  Apply: 53,
  Signature: 54,
  Thumbnail: 55,
  KAddressBook: 56,
  ViewText: 57,
  KGPG: 58,
  PackageDevelopment: 59,
  KFMHome: 60,
  Services: 61,
  Tux: 62,
  Feather: 63,
  Apple: 64,
  W: 65,
  Money: 66,
  Certificate: 67,
  Smartphone: 68,
} as const);

type DefaultIconNumber =
  (typeof DefaultIconNumber)[keyof typeof DefaultIconNumber];

export default DefaultIconNumber;
